package com.neetaspirants.api.service;

import org.springframework.stereotype.Component;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Extracts "@alias" tokens from free-form post/comment text. Aliases are generated by
 * {@link AliasGenerator} as "AdjectiveNoun_123" (letters, then an underscore, then digits),
 * so the pattern matches a leading letter followed by letters/digits/underscore. Matching
 * is purely textual — the caller is responsible for resolving each candidate against
 * AnonymousProfileRepository and ignoring ones that don't correspond to a real profile.
 */
@Component
public class MentionParser {

    private static final Pattern MENTION_PATTERN = Pattern.compile("@([A-Za-z][A-Za-z0-9_]{2,40})");

    public Set<String> extractAliases(String text) {
        if (text == null || text.isBlank()) {
            return Set.of();
        }
        Set<String> aliases = new LinkedHashSet<>();
        Matcher matcher = MENTION_PATTERN.matcher(text);
        while (matcher.find()) {
            aliases.add(matcher.group(1));
        }
        return aliases;
    }
}
